extends Node

enum OPTION { COCOA, MILK, MARSHMELLOWS, WHIPPED_CREAM, STRAW }
enum HOLD { CUP, MILK, MARSHMELLOWS, WHIPPED_CREAM, STRAW, NOTHING }
enum INTERACTABLE { CUPS, STRAWS, COCOA_MACHINE, CUPHOLDER, WHIPPED_CREAM, MILK, MARSHMELLOWS }
